export {
  TuitionApiError,
  getInstitution,
  getInstitutionAnalytics,
  getSegmentAnalytics,
  searchInstitutions,
  type ApiResult,
  type InstitutionSearchQuery,
  type SegmentQuery,
} from "./client";
export type {
  AnalyticsMetrics,
  ApiEnvelope,
  ApiMeta,
  CagrView,
  InstitutionAnalyticsDTO,
  InstitutionAnalyticsScalars,
  InstitutionSearchDTO,
  InstitutionSummaryDTO,
  NetPriceView,
  ProjectionView,
  Residency,
  SegmentAnalyticsDTO,
  SeriesPointDTO,
  YoyView,
} from "./types";
